services:
#    javanais.example:
#        class: Blog\JavanaisBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    blog.twig.javanais_extension:
        class: Blog\JavanaisBundle\Twig\JavanaisExtension
        tags:
            - { name: twig.extension }
